const ENVIRONMENT = "development";
const SERVER_URL = "http://127.0.0.1:5000";
const MULTI_MINT_COUNT = 100;
const UPDATEAUTHORITY_ADDRESS = "5FVEye7HEo7Sq5fQLDuBP4NQKp4uKXUcw8WxERy8nAiF";
const ALLOWED_NFT_NAME = "Candy Cane";

export {
    ENVIRONMENT,
    SERVER_URL,
    MULTI_MINT_COUNT,
    UPDATEAUTHORITY_ADDRESS,
    ALLOWED_NFT_NAME
}